/* ============================================================================
   Branded share card (Phase I growth hook → viral surface). Renders an agent
   artifact into a 1200×630 (OG-ratio) PNG in the locked KushagraOS style, then
   triggers a download. Drawn directly to canvas — no DOM rasterization, no deps,
   deterministic output. Always the luxe dark brand so shared images are
   consistent regardless of the visitor's theme.
   ========================================================================== */

export interface ShareCardInput {
  title: string;
  agentName: string;
  accent: string;
  lines: string[];
}

const W = 1200;
const H = 630;
const PAD = 84;

/** Word-wrap `text` to `maxWidth`, returning at most `maxLines` lines (last one
    ellipsized if it overflows). */
function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number, maxLines: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && line) {
      lines.push(line);
      line = word;
      if (lines.length === maxLines) break;
    } else {
      line = test;
    }
  }
  if (lines.length < maxLines && line) lines.push(line);
  if (lines.length === maxLines && line && lines[maxLines - 1] !== line) {
    let last = lines[maxLines - 1];
    while (ctx.measureText(`${last}…`).width > maxWidth && last.length > 1) last = last.slice(0, -1);
    lines[maxLines - 1] = `${last}…`;
  }
  return lines;
}

async function ensureFonts(): Promise<void> {
  try {
    await Promise.all([
      document.fonts.load("600 64px Fraunces"),
      document.fonts.load("500 24px 'Geist Mono'"),
      document.fonts.load("400 26px 'General Sans'"),
    ]);
    await document.fonts.ready;
  } catch {
    /* fall back to system stacks below */
  }
}

const DISPLAY = `Fraunces, Georgia, "Times New Roman", serif`;
const SANS = `"General Sans", ui-sans-serif, system-ui, sans-serif`;
const MONO = `"Geist Mono", ui-monospace, "SF Mono", monospace`;

/** Draw the card and download it. Returns false if canvas is unavailable. */
export async function downloadShareCard(input: ShareCardInput): Promise<boolean> {
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d");
  if (!ctx) return false;

  await ensureFonts();

  // Background — graphite gradient + accent glow.
  const bg = ctx.createLinearGradient(0, 0, W, H);
  bg.addColorStop(0, "#0A0A0F");
  bg.addColorStop(1, "#131318");
  ctx.fillStyle = bg;
  ctx.fillRect(0, 0, W, H);

  const glow = ctx.createRadialGradient(W * 0.78, -120, 40, W * 0.78, -120, 620);
  glow.addColorStop(0, hexToRgba(input.accent, 0.22));
  glow.addColorStop(1, "rgba(0,0,0,0)");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, W, H);

  // Top row: AYRA mark (left) + product wordmark (right).
  ctx.textBaseline = "middle";
  ctx.fillStyle = input.accent;
  ctx.beginPath();
  ctx.arc(PAD + 8, PAD + 4, 8, 0, Math.PI * 2);
  ctx.fill();
  ctx.font = `600 26px ${MONO}`;
  ctx.fillStyle = "#ECEEF2";
  ctx.fillText("AYRA", PAD + 28, PAD + 4);

  ctx.font = `500 22px ${MONO}`;
  ctx.fillStyle = "#8B8F99";
  ctx.textAlign = "right";
  ctx.fillText("KushagraOS", W - PAD, PAD + 4);
  ctx.textAlign = "left";

  // Title.
  ctx.font = `600 68px ${DISPLAY}`;
  ctx.fillStyle = "#F4F5F8";
  const titleLines = wrap(ctx, input.title, W - PAD * 2, 2);
  let y = 232;
  for (const tl of titleLines) {
    ctx.fillText(tl, PAD, y);
    y += 78;
  }

  // Agent attribution.
  ctx.font = `500 24px ${MONO}`;
  ctx.fillStyle = input.accent;
  ctx.fillText(input.agentName.toUpperCase(), PAD, y + 6);
  y += 52;

  // Body lines.
  ctx.font = `400 27px ${SANS}`;
  ctx.fillStyle = "#C7CAD2";
  const body: string[] = [];
  for (const raw of input.lines) {
    if (body.length >= 5) break;
    for (const w of wrap(ctx, raw, W - PAD * 2, 5 - body.length)) body.push(w);
  }
  for (const bl of body) {
    ctx.fillText(bl, PAD, y);
    y += 40;
  }

  // Footer rule + line.
  ctx.fillStyle = hexToRgba(input.accent, 0.5);
  ctx.fillRect(PAD, H - 96, 64, 3);
  ctx.font = `400 22px ${MONO}`;
  ctx.fillStyle = "#8B8F99";
  ctx.fillText("Generated by KushagraOS · AYRA — Kushagra's AI operating system", PAD, H - 64);

  const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, "image/png"));
  if (!blob) return false;

  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `kushagraos-${slug(input.agentName)}-${Date.now()}.png`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return true;
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "artifact";
}

function hexToRgba(hex: string, alpha: number): string {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex.trim());
  if (!m) return `rgba(191,233,255,${alpha})`;
  return `rgba(${parseInt(m[1], 16)},${parseInt(m[2], 16)},${parseInt(m[3], 16)},${alpha})`;
}
