/* ============================================================================
   ArtifactFrame — the STYLE LOCK (AYRA-SPEC §11). Every agent output renders
   INSIDE this branded frame: AYRA letterhead + "Generated by KushagraOS · AYRA"
   + timestamp, a per-agent signature accent, and a footer CTA that turns every
   demo into a lead. Locked fonts/tokens live in artifacts.css — the model never
   controls how this looks.
   ========================================================================== */

import { useRef, useState, type ReactNode, type CSSProperties } from "react";
import { useOS } from "../lib/store";
import { useIsMobile } from "../hooks/useIsMobile";
import { downloadShareCard } from "../lib/shareCard";
import "./artifacts.css";

/** Minimal identity the branded frame needs. AgentMeta satisfies this, and so
    does Mission Mode's synthetic identity — the Style Lock holds for both. */
export interface ArtifactIdentity {
  id: string;
  name: string;
  role: string;
  accent: string;
}

type Props = { agent: ArtifactIdentity; fallback: boolean; children: ReactNode };

export function ArtifactFrame({ agent, fallback, children }: Props) {
  const openApp = useOS((s) => s.openApp);
  const openMobileApp = useOS((s) => s.openMobileApp);
  const isMobile = useIsMobile();
  const bodyRef = useRef<HTMLDivElement>(null);
  const [saving, setSaving] = useState(false);

  const stamp = new Date().toLocaleString(undefined, {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
  });
  const goContact = () => (isMobile ? openMobileApp("contact") : openApp("contact", "Contact"));

  const saveImage = async () => {
    if (saving) return;
    setSaving(true);
    try {
      const lines = (bodyRef.current?.innerText ?? "")
        .split("\n")
        .map((l) => l.trim())
        .filter(Boolean);
      await downloadShareCard({
        title: `${agent.name} · ${agent.role}`,
        agentName: agent.name,
        accent: agent.accent,
        lines,
      });
    } finally {
      setSaving(false);
    }
  };

  return (
    <article
      className="artifact"
      data-testid="artifact"
      data-agent={agent.id}
      style={{ "--agent-accent": agent.accent } as CSSProperties}
    >
      <header className="artifact__head">
        <span className="artifact__mark">
          <span className="artifact__dot" aria-hidden="true" />
          AYRA
        </span>
        <span className="artifact__role">{agent.name} · {agent.role}</span>
        <span className="artifact__stamp mono">
          Generated by KushagraOS · AYRA · {stamp}
        </span>
      </header>

      <span className="artifact__rule" aria-hidden="true" />

      <div className="artifact__body" ref={bodyRef}>{children}</div>

      <footer className="artifact__foot">
        <p className="artifact__cta-line">
          {fallback ? "Live demo sample — " : "Generated for you just now — "}
          <strong>want this running for your business?</strong>
        </p>
        <div className="artifact__actions">
          <button
            type="button"
            className="artifact__share mono"
            onClick={saveImage}
            data-testid="artifact-share"
            disabled={saving}
            aria-label="Save this result as a branded image"
          >
            {saving ? "Saving…" : "Save image ↓"}
          </button>
          <button type="button" className="artifact__cta" onClick={goContact} data-testid="artifact-cta">
            Initiate a process →
          </button>
        </div>
      </footer>
    </article>
  );
}
